### PR TITLE
Adding SUBPATH support

### PR DESCRIPTION
**Pull request by jasonsyoung**
This simple change allows the user to specify a subdirectory to mount instead of defaulting to the root directory. Tested on a Pixel 4 XL running Android 10.

### CODE REVIEW

**Comment by leso-kn** [comment]
@Geofferey @jasonsyoung What's the status on this, can it be merged?

**Comment by leso-kn** [comment]
Just tested the forked version, mounting a sub directory using `SUBPATH` indeed works as intended.

**Comment by jasonsyoung** [comment]
Yes, should be good to go!

**Comment by PeterNjeim** [comment]
I can't for the life of me get paths with spaces to work. On desktop it works just fine, both rclone mount "/path/to new/point" and /path/"to new"/point work, but /path/to\ new/point does not work. With your modifications on Android, all 3 do not work. It says inaccessible or not found: new/point. It clearly doesn't like the space. Now I can rename the folder, but I would like to delve into what is causing this error elsewhere in the code, before this gets merged

**Comment by PeterNjeim** [comment]
Actually it just isn't working for me, even for space-less paths. The log says: 

> 2021/01/11 07:20:14 ERROR : sftp://pi@192.168.2.37:22/media/Users/peter : Statfs failed: your remote may not support About: failed to run "df -k media/Users/peter\\\r": df: 'media/Users/peter'$'\r': No such file or directory
> : Process exited with status 1

**Comment by jasonsyoung** [comment]
> Actually it just isn't working for me, even for space-less paths. The log says: 
> 
> > 2021/01/11 07:20:14 ERROR : sftp://pi@192.168.2.37:22/media/Users/peter : Statfs failed: your remote may not support About: failed to run "df: 'media/Users/peter'$'\r': No such file or directory
> > : Process exited with status 1

It says your issue right there in the message. You have a carriage return at the end of your SUBPATH value.

`media/Users/peter\\\r":`

Can you post your config? Leave out the password of course.

**Comment by jasonsyoung** [comment]
D'oh! None of the values were ever quoted. I just pushed a commit that quotes everything, so spaces in paths should work now. Sorry about that!

**Comment by jasonsyoung** [comment]
Does @Geofferey or @piyushgarg check Github ever? This has been sitting here for over a year waiting to be merged...

**Comment by Geofferey** [comment]
Sometimes I do ;) , haven't used this module in ages... I merged it in. Hopefully no problems.

**Comment by jasonsyoung** [comment]
> 
> 
> Sometimes I do ;) , haven't used or updated this module in ages... I merged it in indiscriminately. Hopefully no problems.

The man himself! Thank you, it should be all set. I just fixed the spacing issue which I had forgotten to fix long ago. That was the only issue that has ever come from this, so everything should be ok. Please ping me if you ever run into something related to this, but it will be highly unlikely.

**Comment by PeterNjeim** [comment]
@jasonsyoung have you tested this with SFTP? It still won't work for me, no matter what I do, even with space-less paths. Sometimes no error is given both in the terminal and in the log file, and the mounted folder will be empty. Sometimes it gives me the Statfs failed error that I showed above. When spaces are present, it still separates the spaces, giving this error:
> Command mount needs 2 arguments maximum: you provided 3 non flag arguments: ["GCN:/home/pi/media/Users/peter/Saved" "Games/GCN\r" "/mnt/cloud/GCN"]
> Usage:
>   rclone mount remote:path /path/to/mountpoint [flags]

My default SFTP directory is different than my root directory. Normally, you would do `mount:/path` to get a path relative to root, and `mount:path` for paths relative to the default directory. When I put the slash at the beginning when defining the SUBPATH, it puts a double slash in the sftp:// command, leading to an error. What this means is that when I want to use a path relative to root, I have to omit the initial slash, which is counter-intuitive, and even then, Statfs still gives an error saying the path doesn't exist. I tried using paths relative to the default directory, both with and without an initial slash, and I tried manually quoting the SUBPATH variable for all of the 4 types of paths that I just mentioned, none work.

Sometimes, no error is given, making it seem like the SUBPATH worked, but when I open the folder, it shows the default directory. I even set `SUBPATH=`  just to see, and no errors are given, but the folder it creates is empty. I don't know what's going on.

**Comment by PeterNjeim** [comment]
Just tested with GDrive, and it doesn't matter whether I give a valid path or not, no error or log entry is created, and the folder it creates is empty.

I'm looking at the code changes and it looks like nothing should be going wrong. Maybe it's because I'm on Android 11?

**Comment by PeterNjeim** [comment]
I found out the issue, it was my .global.param file. The param `ADD_PARAMS=--fast-list` was the issue. All works well now, with no differences from the desktop syntax

**Comment by jasonsyoung** [comment]
> I found out the issue, it was my .global.param file. The param `ADD_PARAMS=--fast-list` was the issue. All works well now, with no differences from the desktop syntax

Interesting. If it's still separating the paths, it seems as though it's not being quoted. This might be a dumb question, but can you check and make sure the version you have has quotes in the mount call? I pushed that change last minute last night. I'm not sure why fast-list would have fixed that either, they're not related from what I understand.

**Comment by PeterNjeim** [comment]
Yeah it's the latest version from January 11th, and I checked the service.sh file and it's quoted. I actually spoke too soon, removing --fast-list simply fixed my subpath issues in general, the spaces still don't work. But I actually just found another solution, when defining SUBPATH, whenever there's a space, use a back slash \ right before it. This didn't work yesterday due to the --fast-list param, now that that's disabled, using the back slash allows it to work. Maybe another param is messing this up, I'll test some more

**Comment by PeterNjeim** [comment]
Just deleted the .global.param file and spaces don't work normally. I must use a backslash before them. Now that's no big deal, but it's strange to say the least, especially since back slashes, even when quoted, do not work on desktop. Maybe it has to do with how variables are dealt with on Android 11?

**Comment by jasonsyoung** [comment]
> Yeah it's the latest version from January 11th, and I checked the service.sh file and it's quoted. I actually spoke too soon, removing --fast-list simply fixed my subpath issues in general, the spaces still don't work. But I actually just found another solution, when defining SUBPATH, whenever there's a space, use a back slash \ right before it. This didn't work yesterday due to the --fast-list param, now that that's disabled, using the back slash allows it to work. Maybe another param is messing this up, I'll test some more

Thanks for looking into this more. Definitely sounds like this variable is getting passed around or being transformed somehow when being read. Let me do some digging. If  escaping the spaces works, i think I know what to check.

**Comment by mirsella** [comment]
@jasonsyoung what's your problem with the mount ? can you call fusermount from a root shell ?

**Comment by Geofferey** [comment]
I think there was already a method to do this for sftps using aliases...

Screenshot_Chrome_20210126-202040

#2

**Comment by PeterNjeim** [comment]
> I think there was already a method to do this for sftps using aliases...

Wouldn't this method create multiple folders in the Cloud folder, one for the main remote and others for the aliases? I am trying to avoid mounting files I don't need, as Google Photos is indexing files on the remote. Using this newly merged method returns basic rclone command line syntax which was missing, and doesn't create redundancies.

**Comment by Geofferey** [comment]
@PeterNjeim couldn't you disable the main remote?

`DISABLE=1` 

Read all of #2 I'm sorry this stuff is scattered and may not be obvious.

**Comment by PeterNjeim** [comment]
Sorry didn't see that link at the bottom, should've linked that without the screenshot lol, it was taking up my whole screen. Yeah, that's a cool workaround and indeed accomplishes what this pr accomplishes. Still, there's something nice about supporting what rclone already supports syntactically

**Comment by Geofferey** [comment]
@PeterNjeim haha this module shits on rclone, kinda like Android shits on Linux. This is coming from the guy who wrote most of it. It was supposed to dumb rclone down and maybe too much so.

**Comment by chronicsilver23** [comment]
Running sftp on windows and solved this issue by using rclone for windows. rclone mount sftp:/ C:\Users\Chronic\Root. It placed a folder named root in my user folder that I can access.

**Comment by PeterNjeim** [comment]
I recently found out that I could just create a file called `.nomedia` in any folder I would not like applications to index for media, like Google Photos and Onedrive. Can't believe the solution was so simple lol. Now I just mount my whole HDD instead of using SUBPATH, with a `.nomedia` file in the `Cloud` folder, so that all my remotes, not just this HDD, won't be indexed, and hence not destroy my battery life.

**Pull request merged**
